name: build-service-prometheus
team: BLD
phoneBookId: build-service
description: Prometheus-related Containers
authCompartmentOcid: "OCID"

runnerTag: latest
majorVersion: 1
minorVersion: 1

version: ${majorVersion}.${minorVersion}.${BLD_NUMBER}${?BLD_BRANCH_SUFFIX}

triggerOnCommitBranches: ["master", "temp", "main", "pull-requests"]
releaseBranches: ["master", "main","temp"]
snapshotBranches: []
sendNotificationBranches: ["master", "temp", "main", "pull-requests"]
slackChannels: []
bitbucketTag: {"enabled": true, "tagName": ${version}, "description": "Build Service Created Tag"}

dockerRepo: odo-docker-signed-local
helmRepo: shepherd-release-helm-local

steps:
  [
    {
        name: package-helm-chart
        type: make
        makeCommands: [
                { target: all, args: "CHART_NAME=bld-prometheus-server-chart VERSION="${version} },
                { target: all, args: "CHART_NAME=bld-kube-state-metrics-chart VERSION="${version} },
                { target: all, args: "CHART_NAME=bld-prometheus-node-exporter-chart VERSION="${version} },
                { target: all, args: "CHART_NAME=bld-prometheus-t2-adapter-chart VERSION="${version} }
                { target: all, args: "CHART_NAME=bld-cadvisor VERSION="${version} }
        ]

        artifacts: [
            "charts/*.tgz"
        ]
    },
    {
        name: publish-helm-chart
        type: publishgeneric
        repository: shepherd-release-helm-local
        filePathsToPublish: [
            {
                localFile: "charts/*.tgz"
                targetDir: ""
           }
        ]
        dependsOn: package-helm-chart
    }
  ]
